### PR TITLE
fix chocolatey provider correctly handle no newline

### PR DESCRIPTION
**Pull request by jetersen**
seems like chocolatey now outputting newlines when listing --exact

### CODE REVIEW

**Comment by jetersen** [comment]
@patriksvensson 👈 Would be nice to get this in 😊

**Review by patriksvensson — APPROVED** [review]

**Comment by patriksvensson** [comment]
Sorry! 😄

**Comment by jetersen** [comment]
@patriksvensson Sorry I poked, I thought it might be prudent as I know how easy it is to get lost with notification without direct mentions 😄

**Comment by patriksvensson** [comment]
No worries.

**Pull request merged**
